### ISSUE TITLE
Optimize-rdock.py

### ISSUE THREAD

**Issue by NamanChuriwala** [tsudalab/ChemGE#11]
Hi,
I've been running optimize-rdock.py for 1000 iterations to see the kind of fitness scores I get. This is just a subset of the output I'm getting now:
**10000000000.0,CC(F)C1nnnc(N)-[113B@]2=2=2=2nC1[C@@]2cc
-28.3226,CC(N)N1N=NN=S1C1=CC=CC(P(O)SC2=CN=S3OCCOC3=C2)=S1O
-37.7552,CC(O)N1N=NN=S1C1=CC=CC(C(O)SC2=CN=S3NCPOC3=C2)=S1O
10000000000.0,Oc1c(C(Cl)Nc2ccc3c(c2)BPNO3)cncc1S1=NN=NN1C(F)Br
10000000000.0,CC(P)N1N=NN=S1C1=CC=CC(C(O)PC2=CC=S3NCPOS3=C2)=S1O
10000000000.0,CC(Cl)n1nnns1-s1cccc(C(\O)Nc2ccc3c(c2)OPCO3)c7(O)
10000000000.0,PC(F)n1nnns1-s1oncc(C(\O)Nc2ccc3c(c2)BPoO3)c1(O)
-18.2673,Cc1ccc(CSPB(O)Cn2cnc3c(c2=N)C=NC3C)cc1
-22.8559,Oc1c(C(O)Nc2ccc3c(c2)BPNP3)cncc1S1=NN=NN1C(F)P
-24.4896,OC(BC1=CN=S2OSPOC2=C1)C1=S(O)C(S2=NN=NN2C(F)F)=CC=C1
10000000000.0,PC(F)n1nnns1-s1[213N@][n-2]3C-1[C@]2c
10000000000.0,CC(N)n1nnns1-B1cccc(C(\O)Pc2ccs4s(c2)OPCN3)s1(O)
10000000000.0,N=1-Nn1nnns1N-[113B@]2=2=2=2nC1[C@]2cc
-16.488,CC(O)N1N=CN=S1C1=CC=CC(C(O)SC2=CN=S3NCPOC3=C2)=S1O
10000000000.0,OC1=C(C(O)Ic2ccc3c(c2)BPOO3)C=NC=S1S1=NN=NN1C(F)P
10000000000.0,FC(F)n1nnns1-c1cccc(C(\O)Nn2cns3c(c2)OPSO3)s1(O)
-21.7051,BS1=C(C(O)SC2=CN=S3OCOOC3=C2)C=CN=C1S1=NN=NN1C(C)O
10000000000.0,PC(F)n1nnns1-s1cncc(C(\O)Nc2ccc3c(c7)BPnO3)c1(O)
10000000000.0,CC(N)n1nnns1-c1cccc(C(\O)Ns2c[IH-12][2C]OPCN3s1(O))[8o]\3-6-1\2\6
10000000000.0,CC(O)n1nnns1-c8nccc(C(\O)Sc2cns3c(c2)OOCO3)s1(O)
10000000000.0,CC(N)O1N=NN=S1C1=CC=CC(C(O)PC2=CC=S3NCPOS3=C2)=S1O
10000000000.0,CC(F)C1nnnc1-c4cccc(C(\O)Ns2ccc3c(c2)OPPO3)c1(O)
-28.34,OC1=C(C(O)Nc2cc3c(cn2)OOPB3)C=NC=S1S1=NN=NN1C(F)P
10000000000.0,CC(N)n1nnns1-c1cccc(C(\O)Nc2ccs1s(c2)OPCN3)s1(O)
-24.231,CC(N)N1N=NN=S1B1C=CC=C(C(O)PC2=CC=S3NCBOS3=C2)[SH]1O
10000000000.0,CC(O)n1nnns1-c1cccc(C(\O)Sc2cns2c(c2)OPCN3)s1(O)
10000000000.0,CC(O)n8nnns1-c1cccc(C(\O)Sc2cns3c(c2)OPCO3)s1(O)
-16.1475,CC(F)n1nnnc1-c1cccc(C(=O)Nc2ccc3oo[pH]oc3c2)c1O
-27.867,CC(O)N1N=NC[SH]1C1=CC=CC(C(O)SC2=CN=S3NCPOC3=C2)=S1O**

Do the scores look alright? And also, why do I keep getting scores of 10000000000.0 for some smiles? 
Any help is appreciated, Thanks!

**Comment by n-yoshikawa** [comment]
It looks correct. When SMILES is (semantically) invalid, score is set to 10000000000.0.

**Comment by NamanChuriwala** [comment]
Thanks a lot for your swift response
