### ISSUE TITLE
selectParent method

### ISSUE THREAD

**Issue by topazape** [tsudalab/ChemGE#12]
In ChemGE, selectParent method is implemented. But it seems this method is not in use.
How can I use this method ?

$ grep -nir "selectparent"
optimize-rdock-qsub.py:54:def selectParent(population, tournament_size=3):
optimize-rdock.py:55:def selectParent(population, tournament_size=3):
optimize-J.py:54:def selectParent(population, tournament_size=3):

**Comment by n-yoshikawa** [comment]
I previously used that method, but I don't use it in the current version. I just forgot deleting.
