### ISSUE TITLE
unusual  bond 

### ISSUE THREAD

**Issue by gkxiao** [tsudalab/ChemGE#13]
It generated some compounds with unsual bond such as：
 -34.5168 Cn1ncc2c(=O)n(CC(=P)NCCC3=CC=S(O)C=C3)cnc21
![default](https://user-images.githubusercontent.com/12999704/50739991-c6805d00-1222-11e9-8b74-f973ea6cd02a.png)

**Comment by n-yoshikawa** [comment]
We cannot detect unusual bonds if RDKit does not yield any errors. We mentioned this problem in our paper:
> Note that following the grammar alone is not sufficient for generating valid molecules. The validity of
SMILES strings is evaluated by a package like RDKit.
