### ISSUE TITLE
about generation files 

### ISSUE THREAD

**Issue by fe-kim** [tsudalab/ChemGE#14]
Hello,

I tried to generate files that required to execute rDock as mentioned in README.
But can't find binaries pdb2mol, mol2sd, gen_prm in rDock.
'util' directory isn't exist in rDock.
Where can I take them?

rDock was installed successfully. 
After rDock test, I met a msg "Have fun using rDock!!".
And your example python scripts are all done without error.

rDock version : latest(rDock_2013.1)

**Comment by n-yoshikawa** [comment]
Thank you for your issue.
I forgot to upload `pdb2mol`, `mol2sd` and `gen_prm`. I'm sorry.
I will upload necessary files as soon as possible.

**Comment by fe-kim** [comment]
Thanks for your reply :)
Did you make these binaries yourself?
Or someone can make them using rDock?

**Comment by n-yoshikawa** [comment]
I added `util` directory.
You must install Open Babel and Python binding to run them.
If you have any questions, feel free to ask me.

**Comment by fe-kim** [comment]
I checked scripts uploaded.
Thanks a lot for your swift response :)
