### ISSUE TITLE
optimize-rdock.py

### ISSUE THREAD

**Issue by sweetkurapika** [tsudalab/ChemGE#2]
Hi, I was trying to read your code especially in **optimize-rdock.py**
I got confused a little bit in Lines 109-110, if I am not correct, I think there is a typo:
```
109. initial_genes = [CFGtoGene(cfg_util.encode(smiles), max_len=gene_length)
110.                           for s in initial_smiles]
```
in Line 109, do you mean `cfg_util.encode(smiles)` or `cfg_util.encode(s)`?

**Comment by n-yoshikawa** [comment]
Thank you so much for your kind report.
It is a typo. I will fix it soon.
