### ISSUE TITLE
Results of Table 1

### ISSUE THREAD

**Issue by sweetkurapika** [tsudalab/ChemGE#3]
Hi again,
Sorry for having many questions, but I have some interests in your code & paper.
I could successfully run the code, and I checked the results in Table 1 (in the published paper).
You have mentioned that the Table includes:
> the **Maximum score J** at time points 2, 4, 6, and 8 hours achieved by different molecular generation methods. The average values and standard deviations over 10 trials are shown.

I wonder why did choose the Maximum Score instead of the Mean Score? I believe the average values of the Mean score +/- stddev will be more meaningful. If I have some misunderstandings, I hope you clarify the experiments to me. Thank you in advance.

**Comment by n-yoshikawa** [comment]
Thank you very much for your interest.

Mean score is meaningful for population-based methods. But I chose maximum score to compare with other methods. Other methods are not population-based, or look for a single best molecule, so I wanted to compare in the maximum score. In addition, if we can synthesize one molecule, we will choose the best molecule. In that case, only maximum score matters.

**Comment by sweetkurapika** [comment]
@n-yoshikawa thank you for your nice explanation.
I have one more question regarding Table 1.
Since Table 1 includes the experiments in different timings (2h, 4h, 6h and 8h)
The rightmost column "Generation", how was it calculated?

**Comment by n-yoshikawa** [comment]
I'm sorry for the late reply.

Generation is how many generation are processed in 8 hours.
In the log file, the line starting with `$` is a minute-wise log: https://github.com/tsudalab/ChemGE/blob/3ccee1dbfaf1b5a047a7a7792f6282cc4ca518d8/optimize-J.py#L96
The line starting with `%` is a generation-wise log: https://github.com/tsudalab/ChemGE/blob/3ccee1dbfaf1b5a047a7a7792f6282cc4ca518d8/optimize-J.py#L151
We used the biggest generation number before the line starting with `$480`.
https://github.com/tsudalab/ChemGE/blob/3ccee1dbfaf1b5a047a7a7792f6282cc4ca518d8/results/log-J-10000-20000-10#L550 is an example.
