### ISSUE TITLE
Citing relevant literature

### ISSUE THREAD

**Issue by benstaf** [tsudalab/ChemGE#4]
Page 7 of your paper, you use the notion of internal diversity, that I introduced to evaluate generative models, in this paper: 

https://arxiv.org/abs/1708.08227

You even used the same notations!!
![screenshot_20180513-160334](https://user-images.githubusercontent.com/8183572/39968074-6a230fe2-56c7-11e8-9dab-1dfa57e980c0.png)

![screenshot_20180513-160603](https://user-images.githubusercontent.com/8183572/39968079-917fb220-56c7-11e8-98ac-c5f3b5e579df.png)

However, you didn't cite my paper in your bibliography.

Can you correct your paper, and properly cite the literature that you used?

**Comment by n-yoshikawa** [comment]
Thank you for your comment.

We have already included your paper in the bibliography as [10], but citation is missing in this part. We will add citation in the next version.
