### ISSUE TITLE
Error generating files required to execute rDock

### ISSUE THREAD

**Issue by NamanChuriwala** [tsudalab/ChemGE#8]
The first step you describe is as follows:

**Download receptor.pdb and crystal_ligand.mol2 from KITH (DUD-E)**

But **KITH (DUD-E)** shows 404 Error when opened. 
Could you suggest an alternative method?

**Comment by n-yoshikawa** [comment]
There was typo in URL. http://dude.docking.org/targets/kith is correct. I will fix it later. Thank you for your information.
