### ISSUE TITLE
Error running optimize-rDock.py

### ISSUE THREAD

**Issue by NamanChuriwala** [tsudalab/ChemGE#9]
While executing optimize-rDock.py, I get the following warning/error in spite of installing rDock as instructed.

**bin/sh: 1: /home/rDock_2013.1_src/build/exe/rbdock: not found**

Can you help me with this? Thanks!

**Comment by n-yoshikawa** [comment]
I assume that environment variable `$RBT_ROOT` is not set properly. Usually it should be something like `/home/user_name/rDock_2013.1_src`, but username seems to be missing in your case.

**Comment by NamanChuriwala** [comment]
I'm sorry ,I left the username out while posting the error. The error infact  is:

**bin/sh: 1: /home/naman_churiwala_quantiphi_com/rDock_2013.1_src/build/exe/rbdock: not found**

**Comment by n-yoshikawa** [comment]
Does `/home/naman_churiwala_quantiphi_com/rDock_2013.1_src/build/exe/rbdock` exist? If not, rDock is not installed properly. If it exists, maybe it is caused by your environment like a special job control system.

**Comment by NamanChuriwala** [comment]
No, it doesn't exist. I tried re-installing rDock, but it only gives me these folders/files:

**bin  build  data  docs  fw  import  include  INSTALL  lib  license.txt  src**

When I run ls build, I get:

**exemake  libRbt.pro    makefile  Makefile.linux-g++-64-release-exe  make.log   p4utils.pl  test   tmakelib
INSTALL  linux-g++-64  Makefile  Makefile.linux-g++-64-release-lib  makeprogs  progen      tmake**

**Comment by NamanChuriwala** [comment]
Hi,
Since, /home/naman_churiwala_quantiphi_com/rDock_2013.1_src/build/exe/rbdock didn't exist for me, I manually made a directory 'exe' in /home/naman_churiwala_quantiphi_com/rDock_2013.1_src/build and moved rbdock to it from bin. 
Now, optimize-rbdock.py is working for me. Is this the right way of installing rDock though?

**Comment by n-yoshikawa** [comment]
When I installed rDock, there was an exe folder, but it might have changed. I will check.

**Comment by NamanChuriwala** [comment]
Okay, thank you so much

**Comment by n-yoshikawa** [comment]
I was wrong: `$RBT_ROOT/build/exe/rbdock` in rdock_util.py should be `$RBT_ROOT/bin/rbdock`.
I fixed the problem. Thank you for your feedback.
